name: server

on:
  #   schedule:
  #     - cron: "0 20 * * 0-6"
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: RUN
        run: |-
          kill $(lsof -ti:8005)
          RUNNER_TRACKING_ID="" && nohup ./mvnw spring-boot:run &